language: node_js
node_js: 8
sudo: false
cache:
  apt: true
  directories:
  - node_modules
  - bower_components
  - "$HOME/.npm"
before_install:
  - npm install -g polymer-cli
script:
  - polymer lint
